// THE TYPES FILES IS CREATED TO HANDLE ACTION TYPES AVOIDING TYPOS
export const SIGN_IN = 'SING_IN'
export const SIGN_OUT = 'SIGN_OUT'
export const CREATE_STREAM = 'CREATE_STREAM'
export const FETCH_STREAMS = 'FETCH_STREAMS'
export const FETCH_STREAM = 'FETCH_STREAM'
export const EDIT_STREAM = 'EDIT_STREAM'
export const DELETE_STREAMS = 'DELETE_STREAMS'